/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.printPlugin;

public final class R {
    public static final class array {
        public static final int align=0x7f05000b;
        public static final int alignValues=0x7f05000c;
        public static final int feedMode=0x7f050009;
        public static final int feedModeValues=0x7f05000a;
        public static final int fitToPage=0x7f050004;
        public static final int fitToPageValues=0x7f050005;
        /**  P-touch用に追加　 2013/10/01 Start
         */
        public static final int halfCut=0x7f050018;
        public static final int halfCutValues=0x7f050019;
        public static final int halfToning=0x7f050002;
        public static final int halfToningValues=0x7f050003;
        public static final int isAutoCut=0x7f050014;
        public static final int isAutoCutValues=0x7f050015;
        public static final int isCarbon=0x7f050006;
        public static final int isCarbonValues=0x7f050007;
        public static final int isEndCut=0x7f050016;
        public static final int isEndCutValues=0x7f050017;
        public static final int isPeelMode=0x7f050012;
        public static final int isPeelModeValues=0x7f050013;
        public static final int isRotate180=0x7f050010;
        public static final int isRotate180Values=0x7f050011;
        public static final int orientation=0x7f050000;
        public static final int orientationValues=0x7f050001;
        public static final int pjDensityValues=0x7f050008;
        public static final int powermode_array=0x7f05001d;
        public static final int rjDensityValues=0x7f05000f;
        public static final int specialTape=0x7f05001a;
        public static final int specialTapeValues=0x7f05001b;
        public static final int ssp_array=0x7f05001c;
        public static final int valign=0x7f05000d;
        public static final int valignValues=0x7f05000e;
    }
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f030000;
        public static final int activity_vertical_margin=0x7f030001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class string {
        public static final int ErrorMessage_ERROR_NONE=0x7f040040;
        public static final int ErrorMessage_NO_USB=0x7f040045;
        public static final int ErrorMessage_WRONG_OS=0x7f040044;
        public static final int UnableAccess=0x7f040023;
        public static final int about_label=0x7f04002b;
        public static final int about_text=0x7f04002d;
        public static final int about_title=0x7f04002c;
        public static final int ac_adapter=0x7f040096;
        public static final int address_title=0x7f040048;
        public static final int address_value=0x7f040049;
        public static final int alertDialogMessage_runtimeError=0x7f040041;
        public static final int align_title=0x7f04005c;
        public static final int align_value=0x7f04005d;
        public static final int alignmentSettings_title=0x7f04007b;
        public static final int alignmentSettings_value=0x7f04007c;
        public static final int app_name=0x7f040000;
        public static final int battery_charge=0x7f040095;
        public static final int battery_failed=0x7f040091;
        public static final int battery_full=0x7f040092;
        public static final int battery_middle=0x7f040093;
        public static final int battery_weak=0x7f040094;
        public static final int bluetoothPrinterListTitle_label=0x7f04009b;
        public static final int button_add=0x7f040008;
        public static final int button_cancel=0x7f04008e;
        public static final int button_delete=0x7f040009;
        public static final int button_get=0x7f040086;
        public static final int button_get_list=0x7f04000a;
        public static final int button_next_print=0x7f0400a1;
        public static final int button_ok=0x7f04008f;
        public static final int button_print=0x7f040002;
        public static final int button_printer_settings=0x7f040003;
        public static final int button_printer_status=0x7f04000c;
        public static final int button_refresh=0x7f040084;
        public static final int button_remove_template=0x7f040005;
        public static final int button_select=0x7f040007;
        public static final int button_select_file=0x7f040006;
        public static final int button_settings=0x7f040085;
        public static final int button_transfer_template=0x7f040004;
        public static final int button_update=0x7f040087;
        public static final int cancel_printer_msg=0x7f0400a2;
        public static final int chkbox_all_pages=0x7f04001a;
        public static final int chkbox_multiple_select=0x7f040019;
        public static final int close_apl=0x7f04009a;
        public static final int close_connect=0x7f040099;
        public static final int close_message=0x7f04008d;
        public static final int customFeed_title=0x7f04006c;
        public static final int customFeed_value=0x7f04006d;
        public static final int customPaperLength_title=0x7f040068;
        public static final int customPaperLength_value=0x7f040069;
        public static final int customPaperWidth_title=0x7f040066;
        public static final int customPaperWidth_value=0x7f040067;
        public static final int customSetting_title=0x7f04006a;
        public static final int customSetting_value=0x7f04006b;
        public static final int cutSettings_title=0x7f040082;
        public static final int cutSettings_value=0x7f040081;
        public static final int end_message=0x7f04008c;
        public static final int end_title=0x7f04008b;
        public static final int error_input=0x7f04009e;
        public static final int feedMode_title=0x7f04005a;
        public static final int feedMode_value=0x7f04005b;
        public static final int file_explorer_title=0x7f04000b;
        public static final int fitToPage_title=0x7f040054;
        public static final int fitToPage_value=0x7f040055;
        public static final int folder_name=0x7f04009d;
        public static final int halfCut_title=0x7f0400a6;
        public static final int halfCut_value=0x7f0400a7;
        public static final int halfToning_title=0x7f040052;
        public static final int halfToning_value=0x7f040053;
        public static final int ip_mac_title=0x7f040079;
        public static final int ip_mac_value=0x7f04007a;
        public static final int isAutoCut_title=0x7f040074;
        public static final int isAutoCut_value=0x7f040075;
        public static final int isCarbon_title=0x7f040056;
        public static final int isCarbon_value=0x7f040057;
        public static final int isEndCut_title=0x7f040072;
        public static final int isEndCut_value=0x7f040073;
        public static final int isPeelMode_title=0x7f040076;
        public static final int isPeelMode_value=0x7f040077;
        public static final int isRotate180_title=0x7f040070;
        public static final int isRotate180_value=0x7f040071;
        public static final int leftMargin_title=0x7f040062;
        public static final int leftMargin_value=0x7f040063;
        public static final int macAddress_title=0x7f04004a;
        public static final int macAddress_value=0x7f04004b;
        public static final int menu_settings=0x7f040001;
        public static final int msg_title_print=0x7f0400a0;
        public static final int msg_title_warning=0x7f04009f;
        public static final int netPrinterListTitle_label=0x7f04002e;
        public static final int noBluetoothDevice=0x7f040083;
        public static final int noNetDevice=0x7f040024;
        public static final int numberOfCopies_title=0x7f040050;
        public static final int numberOfCopies_value=0x7f040051;
        public static final int orientation_title=0x7f04004e;
        public static final int orientation_value=0x7f04004f;
        public static final int otherSettings_title=0x7f040078;
        public static final int paperSize_title=0x7f04004c;
        public static final int paperSize_value=0x7f04004d;
        public static final int paper_pos_title=0x7f04005e;
        public static final int paper_pos_value=0x7f04005f;
        public static final int pjDensity_title=0x7f040058;
        public static final int pjDensity_value=0x7f040059;
        public static final int pjSettings_title=0x7f04007d;
        public static final int pjSettings_value=0x7f04007e;
        public static final int pj_td_settings_title=0x7f04007f;
        public static final int pj_td_settings_value=0x7f040080;
        public static final int port_title=0x7f040046;
        public static final int port_value=0x7f040047;
        public static final int print_busy_label=0x7f040090;
        public static final int print_succeeded=0x7f040098;
        public static final int printerModel_title=0x7f040042;
        public static final int printerModel_value=0x7f040043;
        public static final int printer_text=0x7f040029;
        public static final int printer_title=0x7f040028;
        public static final int progressDialogMessage_CloseConnection=0x7f040036;
        public static final int progressDialogMessage_CoolingEnd=0x7f040039;
        public static final int progressDialogMessage_CoolingStart=0x7f040038;
        public static final int progressDialogMessage_SetPaper=0x7f040037;
        public static final int progressDialogMessage_WaitingPeel=0x7f04003a;
        public static final int progressDialogMessage_createData=0x7f040030;
        public static final int progressDialogMessage_dataSent=0x7f040034;
        public static final int progressDialogMessage_getting_bluetoothsetting=0x7f04003c;
        public static final int progressDialogMessage_getting_template=0x7f04003f;
        public static final int progressDialogMessage_preparingConnection=0x7f04002f;
        public static final int progressDialogMessage_printed=0x7f040035;
        public static final int progressDialogMessage_removing_template=0x7f04003e;
        public static final int progressDialogMessage_sendingData=0x7f040031;
        public static final int progressDialogMessage_sendingPrintingData=0x7f040032;
        public static final int progressDialogMessage_sendingTemplateData=0x7f04003b;
        public static final int progressDialogMessage_setting_bluetoothsetting=0x7f04003d;
        public static final int progressDialogMessage_startPrint=0x7f040033;
        public static final int progressDialogMsg_communication_start=0x7f040097;
        public static final int progressDialogMsg_transferStart=0x7f04009c;
        public static final int ptOption_title=0x7f0400a5;
        public static final int ptOption_value=0x7f0400a4;
        public static final int rjDensity_title=0x7f04006e;
        public static final int rjDensity_value=0x7f04006f;
        public static final int search_printer=0x7f04008a;
        public static final int setting_PJ=0x7f040027;
        public static final int setting_alignment=0x7f040026;
        public static final int setting_label=0x7f04002a;
        public static final int setting_printer=0x7f040025;
        public static final int special_tape_title=0x7f0400a8;
        public static final int special_tape_value=0x7f0400a9;
        public static final int template_encoding=0x7f0400a3;
        public static final int text_device_setting=0x7f040020;
        public static final int text_input_data=0x7f040010;
        public static final int text_not_exit_template=0x7f040022;
        public static final int text_pdf_pages_end=0x7f040018;
        public static final int text_pdf_pages_start=0x7f040017;
        public static final int text_power_saving=0x7f040089;
        public static final int text_print_image=0x7f04001b;
        public static final int text_print_pdf=0x7f04001c;
        public static final int text_print_template=0x7f04001d;
        public static final int text_remove_template=0x7f040021;
        public static final int text_select_image=0x7f04000f;
        public static final int text_select_pdf=0x7f040016;
        public static final int text_select_pdz=0x7f04000d;
        public static final int text_ssp=0x7f040088;
        public static final int text_template_Index=0x7f040011;
        public static final int text_template_key=0x7f040014;
        public static final int text_template_name=0x7f040012;
        public static final int text_template_replace_texts=0x7f040015;
        public static final int text_template_text=0x7f040013;
        public static final int text_transfer=0x7f04000e;
        public static final int text_transfer_manager=0x7f04001e;
        public static final int text_transfer_pdz=0x7f04001f;
        public static final int topMargin_title=0x7f040064;
        public static final int topMargin_value=0x7f040065;
        public static final int valign_title=0x7f040060;
        public static final int valign_value=0x7f040061;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
